### ISSUE TITLE
Proposal: merge our update on Mauritanian Project 

### ISSUE THREAD

**Issue by slicermauritanie** [NA-MIC/ProjectWeek#1060]
### Project Description

hello  contributors please merge our update on readme for Mauritanian project 
https://github.com/NA-MIC/ProjectWeek/pull/1056
Or invite me to contribute on the project.

**Comment by pieper** [comment]
Hi @slicermauritanie - thanks for posting to the discourse forum.  I'm just back home from project week so I posted a response.  Let's keep the discussion there and hopefully others can chime in and answer any questions you have.

**Comment by jcfr** [comment]
To follow-up, the corresponding pull requests have been consolidated and integrated:
* https://github.com/NA-MIC/ProjectWeek/pull/1062
* https://github.com/NA-MIC/ProjectWeek/pull/1056
* https://github.com/NA-MIC/ProjectWeek/pull/1057
* https://github.com/NA-MIC/ProjectWeek/pull/1058
