### ISSUE TITLE
Project: BAMF nnUNet MRI Breast Model

### ISSUE THREAD

**Issue by rahul99** [NA-MIC/ProjectWeek#1075]
### Draft Status

Ready - team will start page creating immediately

### Category

Segmentation / Classification / Landmarking

### Presenter Location

Online

### Key Investigators

- Rahul Soni (BAMF Health, Singapore)
- Jithendra Kumar (BAMF Health, Singapore)
- Jeff Van Oss (BAMF Health, US)
- Gowtham Murugesan (BAMF Health, US)

### Project Description

We trained an nnUNet model to segment Breast, Fibroglandular Tissue, and Structural Tumor from MRI scans. We prepared the training set from multiple source such as [Breast-MRI-NACT-Pilot](https://wiki.cancerimagingarchive.net/pages/viewpage.action?pageId=22513764), [Duke-Breast-Cancer-MRI](https://wiki.cancerimagingarchive.net/pages/viewpage.action?pageId=70226903), and [ISPY1-Tumor-SEG-Radiomics](https://wiki.cancerimagingarchive.net/pages/viewpage.action?pageId=101942541) 

### Objective

1. `Model Container`: We would like to bring our model resources into a deployable container that can be used by research community to use our models for Breast segmention of MRI Scans
2. `Ease of Use`: Anyone should be able to pull the container (without access issues), mount the input scans and get segmentations
3. `Flexibility`: Target users should be able to get outputs in different formats like `dicom`, `nifti`, `nrrd` etc
4. `Scalability`: Support for single point inference as well as batched inference

### Approach and Plan

We already have trained model weights and a python module that provides an interface for segmentation using the aforesaid model. Next steps for us would be to:
- Publish models weights in Zenodo
- Wrap around segmentation module using Mhub core APIs
- Build and test the container
- Create documentation

### Progress and Next Steps

1. Trained the Breast and tumor segmentation model
2. Wrote a segmentation / inference module using trained model weights
3. Added support for `nifti` and `nrrd` outputs

### Illustrations

Coming soon

### Background and References

Coming soon

**Comment by fedorov** [comment]
> It is nice if you make your models available on Mhub, but for most users it is not a viable option if it still requires docker. You can work with Mhub developers to see if it they can add support for running models without containers.
>
> Alternatively, you can easily run nn-UNet models inside Slicer without docker using the nnunet extension in Slicer. 


@lassoan can you please clarify - are you commenting to inform the submitters of the alternatives available, or because you are opposing initiation of this project? 

I am confident it is the former, but I wanted to be sure.

**Comment by lassoan** [comment]
The project is great, I'm not opposing it at all.

I made suggestions on potential implementation approaches. Cloning another nnunet-based segmentation Slicer extension and changing a few lines of code can be a very simple way of creating an extension for this that allows anybody to easily use the segmentation model on any computer locally. But making the model available also via mhub would be useful, too for example, for running on a shared server.

Probably the best would be if mhub could be used locally, too, without docker, because then it would be available for most users. It would need to check dependencies, install required packages, download models, and offer an API for running segmentation tasks. I believe it can do many of these already.

**Comment by pieper** [comment]
+1 for the option to have mhub models without the docker requirement.  It would open up the models to a wider community of potential users.

**Comment by fedorov** [comment]
I agree it makes sense to consider these options and discuss with @LennyN95! 

Thank you for the feedback!

**Comment by LennyN95** [comment]
Thank you, @lassoan, for sharing your opinion on this.

MHub is built on Docker to lift the burden of setting up the environment for every model at the expense of setting up Docker once. I am aware of the pros/cons of Docker vs. other environment-managing tools like Conda, Singularity, etc. This also greatly depends on the use case (e.g., large-scale batch processing, clinic deployment, data processing in research labs, personal use, etc.). I emphasize that MHub is more than just containerization, and I'm confident that once we establish our core values, they can also be transferred to other systems.

It would be great to have a chat with you, @pieper, @fedorov, @curtislisle, and others during PW :)  
Looking forward to meeting you there!
