### ISSUE TITLE
Proposal: Adding Risk Prediction Models to MHub.ai

### ISSUE THREAD

**Issue by ahmed98adly** [NA-MIC/ProjectWeek#1079]
### Project Description

Adding Sybil Model to predict future cancer incidence risk: https://github.com/reginabarzilaygroup/Sybil/tree/main
Adding CVD-Risk-Estimator Model to predict CVD risk: https://github.com/DIAL-RPI/CVD-Risk-Estimator/tree/master

Risk prediction models is a vital milestone in clinical medicine. Adding risk prediction models to MHub.ai for a flexible and compacted usage could promote reproducible science and innovation in risk prediction models.

**Comment by sjh26** [comment]
Hi @ahmed98adly , if you would like to proceed with this project, don't forget to create a project issue for it.
