### ISSUE TITLE
Project: Integrate MRSegmentator and DeepSpA models into mhub.ai

### ISSUE THREAD

**Issue by FJDorfner** [NA-MIC/ProjectWeek#1085]
### Draft Status

Draft - team will hold off on page creation

### Category

Segmentation / Classification / Landmarking

### Presenter Location

In-person

### Key Investigators

- Felix Dorfner (Charité Universitätsmedizin Berlin, Germany)
- Hartmut Häntze (Charité Universitätsmedizin Berlin, Germany)
- Keno Bressem (Technical University of Munich, Germany)

### Project Description

This project will aim to integrate two models into mhub.ai.

**1. MRSegmentator:** 
- Is a segmentation model that can accurately segment 40 organs and structures in human MRI scans of the abdominal, pelvic and thorax regions. The model works on different sequence types, including T1- and T2-weighted, Dixon sequences and even CT images.
- Paper: [https://arxiv.org/abs/2405.06463](https://arxiv.org/abs/2405.06463)

**2. DeepSpA:**
- Is classification model that incorporates anatomical awareness to detect radiographic sacroiliitis. Detecting radiographic sacroiliitis plays an essential role in diagnosing and classifying axial Spondyloarthritis (axSpA).  
- Paper: [https://arxiv.org/abs/2405.07369](https://arxiv.org/abs/2405.07369)

### Objective

1. Objective: Working implementation of MRSegmentator into the mhub.ai platform.
2. Objective: Working implementation of DeepSpA into the mhub.ai platform

### Approach and Plan

TBD

### Progress and Next Steps

TBD

### Illustrations

Illustrations of both models can be seen on their respective GitHub pages, linked below:

### Background and References

**MRSegmentator:**
- Code: [https://github.com/hhaentze/MRSegmentator](https://github.com/hhaentze/MRSegmentator)
- Paper: [https://arxiv.org/abs/2405.06463](https://arxiv.org/abs/2405.06463)

**DeepSpA:**
- Code: [https://github.com/FJDorfner/Anatomy-Aware-Classification-axSpA](https://github.com/FJDorfner/Anatomy-Aware-Classification-axSpA)
- Paper: [https://arxiv.org/abs/2405.07369](https://arxiv.org/abs/2405.07369)

**Comment by fedorov** [comment]
Very cool! I would love to try this out on some of the images from [Imaging Data Commons](https://portal.imaging.datacommons.cancer.gov/)! I would love to join this project as a tester!

We also have been working on a SynthSeg-based method for MRI segmentation (see preprint here: https://arxiv.org/abs/2403.15609). I think @deepakri201 and @ccosmin97 should be interested to learn more about your approach.

**Comment by FJDorfner** [comment]
Thank you for your interest, it would be great to have you as a tester!

This sounds very interesting. I would like to put you in touch with @hhaentze for that who actually developed the MRSegmentator!

**Comment by surajpaib** [comment]
@FJDorfner Happy to help with this effort as well. I think having some tutorials at the end, say, running the MRSeg on CT & MR images from IDC could be very nice!

**Comment by sjh26** [comment]
Hi @FJDorfner  , this is currently marked as a draft. If it is ready to go please let us know in a comment and we will get the page created

**Comment by FJDorfner** [comment]
Hi @sjh26, thank you very much! The proposal should be ready to go.
