### ISSUE TITLE
Project: Enabling PyTorch3D on Windows and Optimizing Miniconda for Slicer Extensions

### ISSUE THREAD

**Issue by GaelleLeroux** [NA-MIC/ProjectWeek#1090]
### Draft Status

Ready - team will start page creating immediately

### Category

Infrastructure

### Presenter Location

In-person

### Key Investigators

- Leroux Gaelle (University of Michigan, USA)
- Claret Jeanne (University of Michigan, USA)
- Cevidanes Lucia (University of Michigan, USA)
- Hutin Nathan (CPE Lyon, France)
- Allemand David (Kitware, USA)
- Prieto Juan Carlos (University of North Carolina, USA)

### Project Description

This project focuses on enhancing compatibility and usability in two key areas. Firstly, we aim to enable the use of PyTorch3D on the Windows platform. By leveraging the Windows Subsystem for Linux (WSL2) and a virtual Miniconda environment, we intend to bypass the traditional limitations and provide Windows users with full access to PyTorch3D’s capabilities. Secondly, the project seeks to improve the integration of Miniconda with Slicer extensions. Our goal is to simplify the process of creating and managing virtual environments for Slicer extensions, thereby making the procedure more intuitive. This will not only ease the use of various analytical tools and libraries but also streamline the setup process within WSL, especially for tools incompatible with Windows. This approach aims to bridge the gap in functionality and user experience across different platforms.

### Objective

Our project aims to achieve three primary objectives:

Operationalizing PyTorch3D on Windows: The first goal is to make PyTorch3D, typically unsupported on the Windows platform, fully functional. We plan to employ the Windows Subsystem for Linux (WSL2) combined with a virtual Miniconda environment to overcome this limitation. This strategy is designed to provide Windows users with complete access to the extensive functionalities of PyTorch3D.

Improving Miniconda Integration for Slicer Extensions: Our second objective is to enhance the use of Miniconda as a virtual environment manager specifically for Slicer extensions. We aim to streamline the process of creating and managing new virtual environments that are utilized by Slicer extensions, making the procedure more intuitive and user-friendly. This advancement will facilitate the use of specialized libraries required for a variety of analytical tools, which are currently not integrable directly into Slicer. Additionally, this approach will assist in the setup of Miniconda3 and the creation of new environments within WSL, particularly for tools that are not available on Windows.

Updating Modules Previously Unavailable on Windows Due to PyTorch3D: The third goal is to leverage the advancements made in the second objective to update several modules that were previously inaccessible on Windows due to PyTorch3D's limitations. Specifically, we aim to enhance:
- SlicerDentalModelSeg: A module dedicated to the segmentation of teeth.
- SlicerAutomatedDentalTools: Including two key components:
        -  ALI_IOS: Automated Landmarks Identification for Intra Oral Scan.
        -  AREG_IOS: Automated Registration of Intra Oral Scan.

### Approach and Plan

- Investigate PyTorch3D and Windows compatibility, pinpointing causes of incompatibility.
- Catalog PyTorch3D dependencies for WSL2 and outline requisite system configurations.
- Operationalize PyTorch3D on Windows using WSL2 and Miniconda.
- Develop an Automated Installer for WSL2 Setup on Windows.
- Create a Module to Streamline Miniconda for Slicer Extensions
- Update Modules Previously Unavailable on Windows Due to PyTorch3D:
        - SlicerDentalModelSeg: Adapt and validate the module for Windows
        - SlicerAutomatedDentalTools:
                   - ALI_IOS: Ensure compatibility and validate automated landmark identification.
                   - AREG_IOS: Adapt and validate automated registration of intraoral scans.
- Conduct comprehensive testing and validation of all updated modules on Windows.

### Progress and Next Steps

Progress : 
- Completed Initial Research on PyTorch3D and WSL2 Compatibility
- Successfully ran PyTorch3D on WSL2
- Created an installer for WSL2
- Developed SlicerConda, a module to manage Miniconda.
- Updated SlicerDentalModelSeg.
- Updated SlicerAutomatedDentalTools: ALI_IOS.

Next Step:
- Update SlicerAutomatedDentalTools: AREG_IOS.

### SlicerConda Icon
<img src="https://github.com/NA-MIC/ProjectWeek/assets/91245687/0af07dd0-92a1-4231-9b57-9202f41d1d84" alt="CondaSetUp_icon_big_format" width="200" height="200">

**Comment by pieper** [comment]
Thanks for putting this project together.  As I understood from the planning call the source pytorch3d package doesn't provide wheels for windows and you are trying to work around this.  It would be good to know the root reason that wheels aren't available.  There was some discussion that the build process is difficult but it wasn't exactly clear why and maybe that detail could be added to this page.

Also we discussed that WSL2 is not going to be an easy solution for many windows users, as it may be technically difficult or administratively prohibitive on their machines.  For that reason it may have broader usability to explore building pytorch3d as part of the Slicer extension build, where we know exactly which python versions and dependencies are available.

**Comment by lassoan** [comment]
Fully agree, WSL2 would not be an acceptable workaround for most users.

@GaelleLeroux could you please contact the author of pytorch3d to see what is preventing him from supporting Windows wheels? Does he need help with setting up a build system that works for Windows? If we send a pull request that fixes Windows issues, is he going to merge it? Is he then going to create Windows wheels?

**Comment by cpinter** [comment]
> the author of pytorch3d

I think the author is Meta, and from what I heard they are not responsive and the PyTorch3D package can be used "as is" and that's it.

We talked with @GaelleLeroux at the last project week, and it seemed they are committed to follow this approach. I have raised similar concerns, and asked if we could rather collaborate in an alternative way that is more "user friendly". Since then we have worked on another approach for trying to run PyTorch3D on Windows: using ONNX to convert a trained PyTorch3D model and use ONNX Runtime to do the inference, but this attempt was not successful. If you are interested in the partial results the person who worked on this achieved, I can share it (but I have no idea what he did in the last few weeks he worked on this project, as I cannot contact him at all).

**Comment by cpinter** [comment]
Good to know @lassoan . I don't have any personal experience, I just said what my own "subcontractors" told me. It could be worth contacting Jeremy.

**Comment by pty0220** [comment]
Hello everyone,

I'm not sure if you've tried the following method already, but I've been using pytorch3D in Windows-Slicer as follows:

- Create an environment with the same version of Python as Slicer using Anaconda.
- Follow the installation instructions to build pytorch3d in that environment.
- Copy the installed Python\Lib\site-packages\pytorch3d folder to Slicer 5.6.2\lib\Python\Lib\site-packages\pytorch3d.

I've tested this method and it works well. I hope it helps.
