### ISSUE TITLE
Integration of Slicer and ROS

### ISSUE THREAD

**Issue by tokjun** [NA-MIC/ProjectWeek#1091]
### Draft Status

Ready - team will start page creating immediately

### Category

IGT and Training

### Presenter Location

In-person

### Key Investigators

- Junichi Tokuda (BWH)
- Laura Connolly (JHU)
- Anton Deguet (JHU)
- Simon Leonard (JHU)
- Steve Pieper (Isomics)

### Project Description

We will develop a demo system to highlight the features of the SlicerROS2 module.

### Objective

1. Objective A. Describe **what you plan to achieve** in 1-2 sentences.

### Approach and Plan

1. Describe specific steps of **what you plan to do** to achieve the above described objectives.

### Progress and Next Steps

1. Describe specific steps you **have actually done**.

**Comment by pieper** [comment]
@tokjun I hope you don't mind. added myself : )

**Comment by tokjun** [comment]
Of course not! Thanks for joining.
