### ISSUE TITLE
Proposal : Terminologie and 3D Slicer Module to obtaint laleled sulci from T1 Morphologist and for Atlas YEB connect

### ISSUE THREAD

**Issue by sarafv** [NA-MIC/ProjectWeek#1110]
### Project Description

1/ We are rewritting the entire  epiSTIM toolbox (for SEEG procedures) as a 3D Slicer Extension  and adding additional features requested by the clinicians. One of them is the import of labelled sulcis from T1 Morphologist (in Brainvisa Toolbox). To procced, first we need to create a Terminologie for the sulci (and a cbtl? )

2/ It will be nice also to have a 3D Slicer Terminologie for our Basal Ganglia atlas  (YEB Atlas)

**Comment by sjh26** [comment]
Closed wtih #1123
