### ISSUE TITLE
Project: Enhancing the SlicerMorph Hi-Res Screen Capture Module for 3D Slicer

### ISSUE THREAD

**Issue by oothomas** [NA-MIC/ProjectWeek#1127]
### Draft Status

Draft - team will hold off on page creation

### Category

Other

### Presenter Location

Online

### Key Investigators

- Oshane Thomas (Seattle Children's Research Institute, USA)
- Murat Maga (Seattle Children's Research Institute, USA)

### Project Description

The HiRes Screen Capture module in the SlicerMorph extension for 3D Slicer is designed to capture high-resolution screenshots of 3D views. It allows users to specify filename, output folder, and resolution, capturing all visible objects in the selected render window. This functionality is crucial for producing detailed visual documentation of 3D renderings used in research and presentations.

The goal of this project is to prepare the HiRes Screen Capture module for the next update of 3D Slicer by addressing current limitations and enhancing its functionality. Specifically, the project aims to:

- Fix issues causing spontaneous crashes on macOS.
- Correct image resolution errors related to custom display scaling.
- Provide accurate estimates of the scaled output image based on user specifications.
- Ensure stable operation across all major operating systems (Windows, macOS, Linux).

High-resolution screenshots are essential for researchers and professionals who need to present detailed and accurate visual data. Enhancing this module will improve the reliability and usability of 3D Slicer, making it a more robust tool for the scientific community.

### Objective

1. To enhance the HiRes Screen Capture module for 3D Slicer by fixing macOS crash issues, correcting image resolution with custom display scaling, providing accurate scaled output estimates, and ensuring stable operation across Windows, macOS, and Linux.

### Approach and Plan

1. Identify and Fix Crashes on macOS:
    1. Conduct thorough testing to reproduce and identify crash scenarios.
    1. Implement solutions to handle these issues and ensure stable performance on macOS.
2. Correct Image Resolution with Custom Display Scaling:
    1. Investigate how custom display scaling affects screenshot resolution.
    1. Adjust the module to correctly interpret and apply user-defined scaling settings.
3. Provide Accurate Scaled Output Estimates:
    1. Develop principled approach to accurately predict the output image size based on user specifications.
    1. Update the user interface to display these estimates before capturing the screenshot.
4. Ensure Cross-Platform Stability:
    1. Perform extensive testing on Windows, macOS, and Linux.
    1. Resolve any platform-specific issues to ensure consistent and reliable operation.

### Progress and Next Steps

Thus far, the first version of the HiRes Screen Capture module has been integrated into the latest preview version of SlicerMorph. Issues with undisplayed markup and annotations have been resolved. The module is operational except for the aforementioned issues. Users can specify magnification and receive an estimated output resolution before exporting images, although this estimate may be inaccurate if custom display scaling is applied.

### Illustrations

![image](https://github.com/NA-MIC/ProjectWeek/assets/18602669/1d4fc9b0-357e-4f42-a08b-2cbb1a7cb075)

### Background and References

The current version of HiRes Screen Capture can be found at:

https://github.com/SlicerMorph/SlicerMorph/tree/master/HiResScreenCapture

**Comment by sjh26** [comment]
Hi @oothomas  , this is currently marked as a draft. If it is ready to go please let us know in a comment and we will get the page created

**Comment by oothomas** [comment]
Thanks for letting me know, is it possible to do this tomorrow morning after the dev meeting? I would like to clarify a few things before the page is created.

**Comment by sjh26** [comment]
Sure, that's fine I am just reminding people in case they forgot / assumed it was already done.  You can also edit the page after creation, we will be reviewing that during the Project Week call @10 am tomorrow.

**Comment by sjh26** [comment]
@oothomas is this ready to go?

**Comment by oothomas** [comment]
Ah,

Yes it is. Thank you!

Oshane
Sent from my iPhone

On Jun 23, 2024, at 10:13 AM, Sam Horvath ***@***.***> wrote:

﻿

@oothomas<https://urldefense.com/v3/__https://github.com/oothomas__;!!DZ3fjg!42ZhhlcuXMm5Rm5gKn3CpGNCv1D81_P1sPoSGiJ0l1d5k-dzbArufyZRX23SNy1AcOMeBbMKt7A98Cb9cdwPeQ_zSeR2$> is this ready to go?
