### ISSUE TITLE
Project: Simple Editor for Python Scripting

### ISSUE THREAD

**Issue by oothomas** [NA-MIC/ProjectWeek#1128]
### Draft Status

Draft - team will hold off on page creation

### Category

Infrastructure

### Presenter Location

Online

### Key Investigators

- Oshane Thomas (Seattle Children's Research Institute, USA)
- Murat Maga (Seattle Children's Research Institute, USA)
- Steve Pieper (Isomics, Inc, USA)

### Project Description

A built-in simple text editor for python scripts has been discussed on the Slicer forum before. We would like to discuss design issues around this and hope to have a basic prototype (or two) by the end of PW. 

### Objective

1. Support python syntax highlighting
2. Direct highlighted code from the editor to python console (e.g., right click interaction)
3. Embed scripts into the scene.
4. Code autocompletion.

### Approach and Plan

1. Describe specific steps of **what you plan to do** to achieve the above described objectives.
No specific approach has been developed just yet.

### Progress and Next Steps

1. Describe specific steps you **have actually done**.

So far we have a brief web-based mock-up from Steve Pieper:
https://github.com/pieper/SlicerEditor

### Illustrations

![image](https://github.com/NA-MIC/ProjectWeek/assets/18602669/6b06a211-ce37-43db-a56d-64210185b576)

### Background and References

https://discourse.slicer.org/t/support-python-text-highlighting-in-text-module/34511

**Comment by pieper** [comment]
@oothomas @muratmaga this is a great project, hope you don't mind I added myself.  There's a lot more functionality that should be pretty easy to add but I ran out of cycles to investigate.

**Comment by oothomas** [comment]
I'm thrilled you did! I was just about to reach out. I'm really excited about this project and look forward to contributing.

**Comment by sjh26** [comment]
Hi @oothomas  , this is currently marked as a draft. If it is ready to go please let us know in a comment and we will get the page created

**Comment by oothomas** [comment]
Sure!
