### ISSUE TITLE
Project: Evaluation of AI methods for MRI segmentation on IDC data

### ISSUE THREAD

**Issue by ccosmin97** [NA-MIC/ProjectWeek#1132]
### Draft Status

Draft - team will hold off on page creation

### Category

Segmentation / Classification / Landmarking

### Presenter Location

In-person

### Key Investigators

- Cosmin Ciausu (Brigham and Women's Hospital, US)  
- Deepa Krishnaswamy (Brigham and Women's Hospital, US) 
- Andrey Fedorov (Brigham and Women's Hospital, US)

### Project Description

We previously studied the application of a contrast-agnostic approach for MRI/CT abdomen organs segmentation, based on the generation of synthetic data. This synthetic data was then further used as a training set for a fully-supervised U-Net network.
Since this study was performed, other methods aiming to segment MR abdominal organs have been published. Our goal is to evaluate these new methods on IDC MR abdominal-focused data and see how it compares to our method.

### Objective

1. Evaluate performance of MR abdominal organs methods on IDC data.
2. Get feedback on our own method.

### Approach and Plan

1. Select a subset of IDC MR abdominal-focused IDC data.
2. Create evaluation notebooks for newly published methods on this subset.
3. Compare to our method.

### Progress and Next Steps

1. Describe specific steps you **have actually done**.

### Background and References

- Our method 
  - [Towards Automatic Abdominal MRI Organ Segmentation: Leveraging Synthesized Data Generated From CT Labels](https://arxiv.org/abs/2403.15609)
- New published methods
  - [MRSegmentator: Robust Multi-Modality Segmentation of 40 Classes in MRI and CT Sequences](https://arxiv.org/pdf/2405.06463)
  - [TotalSegmentator MRI: Sequence-Independent Segmentation of 59 Anatomical Structures in MR images ](https://arxiv.org/abs/2405.19492)
  - [MRISegmentator-Abdomen: A Fully Automated Multi-Organ and Structure Segmentation Tool for T1-weighted Abdominal MRI](https://arxiv.org/abs/2405.05944)
  - [TotalVibeSegmentator: Full Torso Segmentation for the NAKO and UK Biobank in Volumetric Interpolated Breath-hold Examination Body Images](https://arxiv.org/abs/2406.00125)

**Comment by sjh26** [comment]
Hi @ccosmin97  , this is currently marked as a draft. If it is ready to go please let us know in a comment and we will get the page created

**Comment by ccosmin97** [comment]
Hi @sjh26, yes sorry for the delay, the draft is ready!
