### ISSUE TITLE
Project: epiSTIM as 3d slicer extension

### ISSUE THREAD

**Issue by MartBony** [NA-MIC/ProjectWeek#1146]
### Draft Status

Draft - team will hold off on page creation

### Category

Other

### Presenter Location

Online

### Key Investigators

- Carole-Anne COS (ICM, France)
- Martin GREGORIO (ICM, France) 
- Sara FERNANDEZ VIDAL (ICM, France)

### Project Description

We are proposing a new extension to 3D Slicer designed to help clinicians and researchers to manage neuroimaging data needed for SEEG procedures. This is a 3d slicer extension that is based on former code from the epiSTIM project by Sara Fernandez Vidal.

**SEEG Introduction** : Intracerebral electrodes are used in the context of stereo-electroencephalography (SEEG) recordings in patients with pharmacoresistant epilepsy. SEEG is an invasive method used to determine which anatomical structures of the brain generate epileptic seizures. SEEG is usually used when non-invasive explorations are inconclusive. A precise localization and 3D visualization of brain anatomy is crucial to precisely plan intracerebral electrode trajectories and then localize the origine and spreading of the seizures. 

### Objective

Bundle all our previous sparse code into a self-contained slicer extension that works with docker.

### Approach and Plan
Our previous work focused on converting existing code (epiSTIM) into user friendly slicer modules that loosely work with each other. We used the software docker to bundle parts of the processing to improve portability and version handling. Docker images were used to run Brainvisa, Freesurfer and Fastsurfer, sMRIprep, and more.

**Plan**
- Clean up the current code and create a general repo of all our individual modules. 
- Research the process of bundling our modules into an extension. 
- Build the extension.
- Determine a platform for the application to run on : Personal computers of clinicians or a server.

### Progress and Next Steps

Several key modules have already been written for the SEEG pipeline. Some are to be finished before the week so that we can concentrate on the extension.

### Illustrations

![SEEGetEpiSTIM EN](https://github.com/NA-MIC/ProjectWeek/assets/45314202/08031a72-d90d-45e1-a7a1-76a281b43e6f)

**Comment by sjh26** [comment]
Hi @MartBony , this is currently marked as a draft. If it is ready to go please let us know in a comment and we will get the page created.

**Comment by MartBony** [comment]
Hi @sjh26, we're done, you can create the page !
