### ISSUE TITLE
Visual Model for Respiratory Motion of Airways with SOFA-Slicer

### ISSUE THREAD

**Issue by Quilliams85** [NA-MIC/ProjectWeek#1156]
### Category

VR/AR and Rendering

### Presenter Location

In-person

### Key Investigators

- Quinn Williams (Brigham and Woman's Hospital, USA)
- Steve Pieper (Isomics, Inc., USA)

### Project Description

Integration of a softbody physics simulation of lung movement during breathing in SOFA into slicer. It will be used as a virtual reference for bronchoscopy alongside streamed camera data.

### Objective

1. Integrate current simulation into the slicer with the slicer-SOFA extension
2. Refine the respiratory motion
3. Create UI elements to control breathing parameters
4. Sync camera position data with a virtual camera in the airways
5. Define a standard pipeline from segmentation to simulation for further bronchoscopy procedures

### Approach and Plan

1. Talk with slicer-sofa devs to understand the communication with sofa and slicer
2. Talk with SOFA devs for advice on lung physics in SOFA
3. Script the UI elements for the simulation
4. Figure out whether creating a virtual camera is benificial
5. Create a write-up on the process used to create the simulation and how to recreate it

### Progress and Next Steps

1. Created lung and airway segmetations from pig CT scan
2. Optimized airway mesh and created volumetric mesh
3. Configured a SOFA simulation using the airway segmentation
4. Created a diaphragm spring/damper force system to emulate airway movement

### Illustrations

![Current airway movement simulated with SOFA](https://github.com/NA-MIC/ProjectWeek/assets/63506358/2e408192-19b0-477f-8939-5a102cd10cff)

### Background and References

- [https://github.com/Quilliams85/Lung-Simulation-SNR-Lab.git](https://github.com/Quilliams85/Lung-Simulation-SNR-Lab.git)

**Comment by sjh26** [comment]
Hi @Quilliams85, this is currently marked as a draft. If it is ready to go please let us know in a comment and we will get the page created

**Comment by Quilliams85** [comment]
Hi @sjh26 , sorry for taking a while to respond to this! I met with Steve Pieper today to clarify a few of the project details. This should be good to go now! Thanks.
