### ISSUE TITLE
Project: An IGT Masters course based on Slicer

### ISSUE THREAD

**Issue by drouin-simon** [NA-MIC/ProjectWeek#1189]
### Draft Status

Ready - team will start page creating immediately

### Category

IGT and Training

### Presenter Location

In-person

### Key Investigators

- Simon Drouin (ETS, Canada)
- Rafael Palomar (Oslo University Hospital / NTNU, Norway)

### Project Description

The goal of this project is to improve the lecture and demo material for the Master's level at ETS Montreal entitled "Surgical Technologies" (see course website [here](https://www.etsmtl.ca/etudes/cours/gts880a), in French). 

The objective of the "Surgical Technologies" course is to familiarize students with the technologies that enable the planning and execution of minimally invasive surgical operations. These technologies combine various medical imaging acquisition techniques, precise image processing, 3D tracking of surgical tools, and several mechanisms and algorithms that allow for the alignment and visualization of this information, enabling surgeons to perform the most precise and minimally invasive operations possible for their patients.

By the end of the course, students expected to:
- Understand the operating principles and limitations of the various devices involved in surgical guidance systems;
- Understand the main algorithms used during the planning and guidance of minimally invasive operations and their limitations;
- Analyze the context and constraints of a new clinical application and propose a design based on the software and hardware components studied;
- Design and implement a simple prototype guidance system for a specific clinical application.

The practical work in the course is all based on the use of 3D Slicer.

### Objective

1. Identify existing tutorials that can help students of the course learn about the Slicer features they can take advantage of in their term project
2. List existing surgical technologies that are not already covered in the class and determine whether a prototype can easily be built based on existing Slicer modules.
3. List publicly available datasets that can be used to build IGT prototypes for different types of procedures. 

### Approach and Plan

1. Find people who have an interest in a similar course and discuss material they already have to train people, even in other context
2. List existing tutorial and new material on this page
3. Identify a format that would enable the sharing of course material under a creative commons license (pick a licence)
4. List existing sources of publicly available medical images and their surgical application

### Progress and Next Steps

1. Describe specific steps you **have actually done**.

**Comment by mauigna06** [comment]
You could think about adding BRP to the list:
https://github.com/SlicerIGT/SlicerBoneReconstructionPlanner

I'm going to try to deliver a new version of the videotutorial next week:
https://youtu.be/g9Vql5h6uHM

It is not navigation though it's patient-matched surgical guides
