### ISSUE TITLE
Usage of `light-torch`

### ISSUE THREAD

**Issue by pmeier** [NA-MIC/ProjectWeek#306]
It seems that you want to use `light-the-torch` after @fepegar submitted a patch and to other projects as well. Is everything now working as intended or is there something else need to be fixed on my end?

If not, I would push a release so that you simply can `pip install light-the-torch`.

**Comment by fepegar** [comment]
Hi, @pmeier. Thanks for asking! It should be fine once the steps in https://github.com/Slicer/Slicer/issues/5705#issuecomment-867736846 are implemented. Then, if you push the new release, we should be able to install PyTorch inside Slicer like this:

```python
pip_install('light-the-torch')
import light_the_torch as ltt
wheel_url = ltt.find_links(['torch'])[0]
pip_install(wheel_url)
```

@lassoan, do you think the PythonQt issue will be fixed for Project Week? Also, I guess this issue should be moved to https://github.com/Slicer/Slicer.

**Comment by jcfr** [comment]
> do you think the PythonQt issue

Are you taking about addressing this comment ? See  https://github.com/Slicer/Slicer/issues/5705#issuecomment-867736846

**Comment by fepegar** [comment]
> Are you talking about addressing this comment ?

Yes. I wouldn't know how to do it, it looked like Andras was going to tackle it. Happy to help if there's something you think I can do.

**Comment by jcfr** [comment]
I am taking care of it now.

**Comment by jcfr** [comment]
Closing. This will be addressed in https://github.com/Slicer/Slicer/pull/5711
