### ISSUE TITLE
Proposal: Extension for recurrent lung infections

### ISSUE THREAD

**Issue by mady27** [NA-MIC/ProjectWeek#609]
### Project Description

Yes, in fact the clinical problem is that in our context we often receive patients who have repeated infectious episodes. So, to assess the severity of the pulmonary involvement on the X-ray, it is difficult for us to know the limit between the old and the new lesions, especially since the patients often lose the previous images.

Thus with the 3d slicer, by making a comparative study between the old and recent lesions, one can create an extension capable from the thresholding, of coloring the zones differently.

This can be of great use to us!

**Comment by curtislisle** [comment]
I have done some work with radiomics (extracting numerical features) from lung CT scans.  It is possible the radiomics values of early and later X-ray scans could be compared and a model trained to separate healthy from diseased state.  I haven't looked, but I am sure there are papers on similar approaches.

**Comment by jcfr** [comment]
If it makes sense, would it be possible to update the project page with additional details.

In the project description it is mentioned the following:

> In order to use the extension in pulmonology to correlate a recent symptomatology with an X-ray image having images related to old infections

Question: Is there already an existing extension or was the original plan to develop a new extension ?


References:
* https://github.com/NA-MIC/ProjectWeek/edit/master/PW39_2023_Montreal/Projects/ExtensionForRecurrentLungInfections/README.md
* https://projectweek.na-mic.org/PW39_2023_Montreal/Projects/ExtensionForRecurrentLungInfections/

**Comment by jcfr** [comment]
:eyes: Friendly ping

**Comment by mady27** [comment]
It's an original extension project
