### ISSUE TITLE
Proposal: Working with DICOM annotations

### ISSUE THREAD

**Issue by DanielaSchacherer** [NA-MIC/ProjectWeek#618]
### Project Description

I plan to create tutorials on how to work with DICOM annotations in pathology whole-slide images (WSIs). Two formats of DICOM annotation objects, i.e. Microscopy Bulk Simple Annotations and Segmentation, both currently under development will be used and I will try to eventually summarize advantages and disadvantages of each format for different use cases. 

Most likely, @cpbridge and @dclunie, who develop the DICOM annotations, will support with their expertise and there might be some synergies with the project of @maxfscher and the project of @curtislisle.

**Comment by fedorov** [comment]
We discussed this further with Daniela, and agreed it also makes sense to include parametric map in the scope of this project. Daniela will work on calculating nuclei density from the annotations we have, and the result can be stored as a parametric map - hope this will be of interest to you @maxfscher.

Also, for the sake of completeness, this is the collection that contains the annotations that are being converted into DICOM representation (both bulk annotation and binary segmentations): https://doi.org/10.7937/TCIA.2019.4A4DKP9U.

**Comment by fedorov** [comment]
@DanielaSchacherer this is the issue that was mentioned in the call today: https://github.com/ImagingDataCommons/slim/issues/154

**Comment by curtislisle** [comment]
This proposed work is very interesting to me as I plan to bring models that generate segmentation bitmaps from DOCOM-WSI images, but I am not experienced in writing DICOM objects.  Looking forward to collaborating.

**Comment by CPBridge** [comment]
Happy to support this!

**Comment by DanielaSchacherer** [comment]
Proposal ended up in this project: https://github.com/NA-MIC/ProjectWeek/issues/661
