### ISSUE TITLE
Project: Tracked ultrasound integration into NousNav, a low-cost neuronavigation system

### ISSUE THREAD

**Issue by ColtonBarr** [NA-MIC/ProjectWeek#625]
### Category

IGT and Training

### Key Investigators

- Colton Barr (Queen's University / BWH)
- Sarah Frisken (BWH)
- Sonia Pujol (BWH)
- Steve Pieper (Isomics)
- Tina Kapur (BWH)
- Tamas Ungi (Queen's University)
- Sam Horvath (Kitware)

### Project Description

NousNav is an ongoing project led by Dr. Alex Golby at Brigham and Women's Hospital to build and disseminate a low-cost neuronavigation system. Built as a 3D Slicer Custom App, NousNav uses low cost optical tracking (Optitrack Duo) in combination with custom optically-tracked tools and reference arrays to facilitate patient registration, procedure planning, and navigation. 

The system is being continually updated based on user feedback. An important next step in development is the integration of tracked ultrasound data.

### Objective

1. Gather user feedback on the current iteration of the system and establish potential next steps for development.
2. Discuss approaches for integrating tracked ultrasound data into the navigation workflow.
3. Create a NousNav prototype that includes tracked ultrasound.

### Approach and Plan

1. Setup demo of NousNav system for participants to try and systematically collect user feedback.
2. Collaborate with colleagues working on tracked neurosurgical ultrasound to establish best practices for integrating ultrasound into the system
3. Create custom build of NousNav with basic tracked ultrasound workflow elements integrated.

**Comment by sjh26** [comment]
can you add the countries for each investigator, i.e 
`Sam Horvath (Kitware, USA)`
