### ISSUE TITLE
Project: Histology AI models imported into IDC

### ISSUE THREAD

**Issue by curtislisle** [NA-MIC/ProjectWeek#645]
### Category

Segmentation / Classification / Landmarking

### Key Investigators

- Curtis Lisle, KnowledgeVis (USA)
- Daniela Schacherer, MEVIS (Germany)
- David Clunie, PixelMed (USA)
- Maximillian Fischer, DKFZ (Germany)

### Project Description

This project focuses on importing whole slide image (WSI) histology images and trained deep learning models into the Imaging Data Commons for access by others. We have developed tissue-level segmentation models for detecting subtypes of rhabdomyosarcoma (RMS) in whole slides. Our project is releasing WSIs and the corresponding models trained on the slide images.    

This project will test reading DICOM-WSI imagery (including compression) and focus on how to write out model segmentation results as DICOM-WSI annotations for upload to IDC.   We also have classification and regression models, so we need to decide how to write non-imagery classification results as DICOM, as well.  

### Objective

- Write out model segmentation image results as DICOM-WSI Segmentation or Parametric Map objects
- Test models on sample DICOM-WSI images
- Determine where to how to store regression and classification model results as DICOM annotations

### Approach and Plan

- Verify the algorithms run on DICOM-WSI source images (including compression)
- Understand the semantics associated with DICOM Segmentation and Parametric Map objects
- Write output formatter to generate proper DICOM for single class and multi-class segmentation images

### Progress and Next Steps

- Gather source images in DICOM-WSI format
- Gather model source and pre-trained weights for inferencing

### Background and References

models wrapped in a girder3 web application: https://github.com/knowledgevis/rms_infer_web

**Comment by fedorov** [comment]
@curtislisle to confirm, you would like those annotations to be ingested into IDC eventually, right?

**Comment by fedorov** [comment]
IDC is **not** the place to share models. IDC **is** the place to share analysis results of established value and quality, produced by models.

**Comment by curtislisle** [comment]
@fedorov , yes, we would like to be able to save the annotations with the source imagery into IDC if this makes sense according to IDC. We were planning to make the models available as examples in colab notebooks, as well.

**Comment by fedorov** [comment]
> we would like to be able to save the annotations with the source imagery into IDC if this makes sense according to IDC. 

I would then recommend changing the title to "Histology AI analysis results imported into IDC". IDC does not host models.

Happy to join this project to help with the related topics!
