### ISSUE TITLE
Proposal:  Using large language AI models to invoke Slicer modules and workflows

### ISSUE THREAD

**Issue by curtislisle** [NA-MIC/ProjectWeek#648]
### Project Description

3D Slicer is built with a powerful core to load, transform, and store manage medical images and derived datasets.  Slicer has a catalog of loadable extensions that assist with or automate task-specific workflows.  Slicer's web API provides remote access to invoke many of the processing steps which are available through its very complete user interface.    

The recent explosion of generative LLMs (large language models) from the AI community has demonstrated that these language models can, in some cases, translate task or problem descriptions into sequences of operations.  Wouldn't it be powerful if 3D Slicer could be verbally instructed to perform operations or process datasets as requested?  Theoretically, an embedded LLM could be trained on Slicer's modules, including under what circumstances the modules could be applied to transform a Slicer scene as needed to solve a problem presented by the user.

As one example, in Operating Theaters during surgical procedures, the Slicer user interface is hard or impossible to access due to sterility restrictions and other factors.  It would be helpful if clinicians could control Slicer's functions through an alternative method than the interactive user interface.    For example, "Let me see the lung lesions more clearly" could be translated into increased transparency of the lung segmentation and an orientation repositioning to make a lesion segmentation visible in-situ. 

A goal of this project proposal would be to schedule a meeting during Project Week to discuss this idea, assess the level of interest in the Slicer community, discuss early technical approaches, and decide who might be interested in working together to seek funding to pursue this together.  Both clinicians with a problem to solve and AI technicians would be invited to participate.

**Comment by pieper** [comment]
Hi @curtislisle - I'll be very interested in discussing this!

**Comment by pieper** [comment]
Here's a related post: https://nickarner.com/notes/llm-powered-assistants-for-complex-interfaces-february-26-2023/

**Comment by curtislisle** [comment]
I like this post, @pieper.

Hugging Face has a new API called "Agents" that is designed to use tools according to their descriptions of the I/O they handle.  The Agent API puts together a workflow of tools to accomplish the users request.  This is not exactly what I was thinking, as there are issues related to how to identify and return a changed MRML scene, but it inspired my thinking somewhat:  https://huggingface.co/docs/transformers/transformers_agents. 

Work that is more directly towards a way to invoke Slicer modules via API is Gorilla, a LLAMA model fine-tuned to invoke external APIs to accomplish a requested task:   https://github.com/ShishirPatil/gorilla.  I just started reading the paper referenced on the repository site.

**Comment by sjh26** [comment]
closed with #744
