### ISSUE TITLE
Proposal: Translation/rotation of select points in a list.

### ISSUE THREAD

**Issue by smrolfe** [NA-MIC/ProjectWeek#649]
### Project Description

The goal of this project is to enable creation of synthetic data from landmark transforms. 

Given a point list, the user will select points to be operated on. The selected points will be moved independently to create the target landmark set for the transform.

This can currently be done in the Markups module by copying the points to a new list, translating/rotating the points, and copying the point positions back to the original node. However this process can be tedious and error-prone. We plan to implement this function as an option in the Markup Editor module in the SlicerMorph extension.

This project proposal is related the forum post [here](https://discourse.slicer.org/t/moving-a-subset-of-points-in-a-list/29198)

**Comment by sjh26** [comment]
Closing with #679
