### ISSUE TITLE
Project: MHub-Slicer Integration

### ISSUE THREAD

**Issue by denbonte** [NA-MIC/ProjectWeek#659]
### Category

Segmentation / Classification / Landmarking

### Key Investigators

- Leonard Nürnberg (Department of Radiology, Brigham and Women’s Hospital, Boston, MA)
- Dennis Bontempi (Department of Radiology, Brigham and Women’s Hospital, Boston, MA)
- Justin Johnson (Department of Radiology, Brigham and Women’s Hospital, Boston, MA)
- Andrey Fedorov (Department of Radiology, Brigham and Women’s Hospital, Boston, MA)

### Project Description

MHub is a repository of self-contained deep-learning models trained for a wide variety of applications in the medical and medical imaging domain. MHub provides the community with reproducible and transparent AI pipelines that work out of the box as intended by the developers.

As part of our efforts, we developed a first version of a Slicer MHub extension that allows users to run different AI models directly in Slicer without the need to install potentially conflicting dependencies as part of their Slicer Python installation.

### Objective

The goal of this project is to polish the extension, publish it, and further explore its potential applications and user feedback to expand the extension's capabilities, address its limitations, and ensure its seamless integration with Slicer.

### Approach and Plan

Work on identified issues/enhancements, and collect feedback from the Slicer community.

### Illustrations

![image](https://github.com/NA-MIC/ProjectWeek/assets/31729248/a437e55a-4772-4cc8-862f-455241d03014)

**Comment by pieper** [comment]
@denbonte - this looks very cool.  I have an nnU-Net model that's starting to work.  Do you have a recipe for wrapping it up to use with mhub?

**Comment by denbonte** [comment]
Hey Steve!

> I have an nnU-Net model that's starting to work. Do you have a recipe for wrapping it up to use with mhub?

Awesome! We're writing the docs as of now, and will provide numerous examples on how to do this. For nnU-Net models this is going to be very very easy (thanks to the work @LennyN95 has done with the MHubIO framework).

I suggest we discuss in person at the project week? If everything is set and you can provide the weights, it's probably going to be an half-an-hour task 🙃 

CC'ing @fedorov!

**Comment by pieper** [comment]
Yes, sounds excellent!
