### ISSUE TITLE
Project: Tutorials on working with DICOM annotations in pathology whole-slide images

### ISSUE THREAD

**Issue by DanielaSchacherer** [NA-MIC/ProjectWeek#661]
### Category

Segmentation / Classification / Landmarking

### Key Investigators

- Daniela Schacherer (Fraunhofer MEVIS, Germany) 
- Chris Bridge (MGH, USA)
- David Clunie (PixelMed, USA)
- Curtis Lisle (KnowledgeVis, USA)
- Maximillian Fischer (DKFZ, Germany)
- Andrey Fedorov (BWH, USA) 

### Project Description

This project aims to create tutorials on how to work with DICOM annotations in pathology whole-slide images (WSIs). 
At first, we will focus on nuclei annotations stored as DICOM Microscopy Bulk Simple Annotations and compute nuclei density (cellularity) on tile-level from them. The computed cellularity values are then stored as DICOM parametric maps. 

### Objective

1. Objective A: Have a Colaboratory notebook ready that at least reads DICOM Microscopy Bulk Simple Annotation files (currently from a Google Storage bucket, ideally later from the IDC directly) and computes cellularity values. 
2. Objective B: Encode computed cellularity values as DICOM parametric map that can be stored back to the IDC.   

### Approach and Plan

1. Investigate nuclei annotations for plausibility 
2. Read nuclei annotations 
3. Efficiently compute cellularity values 
4. Encode cellularity values as DICOM parametric maps 

### Progress and Next Steps

1. Describe specific steps you **have actually done**.

**Comment by fedorov** [comment]
@DanielaSchacherer since the resulting tutorials will be about data in IDC, and will accompany IDC, I would be very interested to be involved - even though I do not have subject expertise in pathology.
