### ISSUE TITLE
Proposal: add google maps link to venue page

### ISSUE THREAD

**Issue by pieper** [NA-MIC/ProjectWeek#685]
### Project Description

The new venue info is helpful, but could someone add a link with the actual location populated so that people can easily get directions?  @drouin-simon ?

https://projectweek.na-mic.org/PW39_2023_Montreal/#venue

**Comment by sjh26** [comment]
@drouin-simon @pieper Is this the location we decided was correct?

https://goo.gl/maps/xNedgMBt4C6jwiCu5

**Comment by pieper** [comment]
That sure looks right to me.  I'll update and then if @drouin-simon says it needs to be changed we can always update it.
