### ISSUE TITLE
Project: Defining and Prototyping "Labelmap" Segmentations in DICOM Format

### ISSUE THREAD

**Issue by CPBridge** [NA-MIC/ProjectWeek#710]
### Category

Segmentation / Classification / Landmarking

### Key Investigators

- Chris Bridge (MGH/Harvard, USA)
- Steve Pieper (Isomics, USA)
- David Clunie (PixelMed, USA)
- Andrey Fedorov (BWH/Harvard, USA)

### Project Description

The DICOM Segmentation format is used to store image segmentations in DICOM format. Using DICOM Segmentations, which use the DICOM information model and can be communicated over DICOM interfaces, has many advantages when it comes to deploying automated segmentation algorithms in practice. However, DICOM Segmentations are criticized for being inefficient, both in terms of their storage utilization and in terms of the speed at which they can be read and written. This is in comparison to other widely-used segmentation formats within the medical imaging community such as NifTi and NRRD.

While improvements in tooling may alleviate this to some extent, there appears to be an emerging consensus that changes to the standard are also necessary to allow DICOM Segmentations to compete with other formats. One of the major reasons for poor performance is that in segmentation images containing multiple segments (sometimes referred to as "classes"), each segment must be stored as an independent set of binary frames. This is in contrast to formats like NifTi and NRRD that store "labelmap" style arrays in which a pixel's value represents its segment membership and thus many (non-overlapping) segments can be stored in the same array. While the DICOM Segmentation has the advantage that it allows for overlapping segments, in my experience the overwhelming majority of segmentations consists of non-overlapping segments, and thus this representation is very inefficient when there are a large number of segments.

The goal of this project is to gather a team of relevant experts to formulate changes to the standard to address some issues with DICOM Segmentation. We will focus primarily on "Labelmap" style segmentations and issues surrounding frame compression. Other objectives for further discussion include simplifying per-frame metadata. Although we do not speak for the DICOM standards committee, we hope to put forward a complete proposal that can be considered by the committee. Ideally, the proposal will be backed by multiple interoperable implementations of the proposed objects and demonstrations of their value in reducing object size and complexity.

The proposal for this project received a considerable amount of constructive feedback from the community: #643 

@pieper @fedorov @dclunie

### Objective

1. Put forward a proposal for changes to the DICOM Segmentation object that addresses the needs of the medical image computing community

### Approach and Plan

1. Gather relevant experts to discuss and appraise potential changes to the DICOM standard for Segmentations
2. Compile a full proposal based on the resulting consensus from the team
3. Implement prototypes of the new proposed objects in the highdicom (python) and dcmjs (javascript) libraries
4. Use the prototype implementations to demonstrate the advantages of the proposed changes on realistic data (e.g. in terms of file size, read/write times)

### Progress and Next Steps

1. Solicited feedback and items for discussion on proposal #643

**Comment by dclunie** [comment]
Here is a draft New Work Item Proposal on Label Map Segmentation for the DICOM Standards Committee - please suggest edits as you see fit:

[https://docs.google.com/document/d/1_6nefzEaWZ-its-GILNKtxT0k9lzIVOrsnrPpR5Vwxw/edit](https://docs.google.com/document/d/1_6nefzEaWZ-its-GILNKtxT0k9lzIVOrsnrPpR5Vwxw/edit)
