### ISSUE TITLE
Project: SystoleOS

### ISSUE THREAD

**Issue by RafaelPalomar** [NA-MIC/ProjectWeek#724]
### Category

Infrastructure

### Presenter Location

In-person

### Key Investigators

- Rafael Palomar (Oslo University Hospital, Norway)
- Steve Pieper (Isomics, USA)

### Project Description

Over a span of more than ten years, 3D Slicer has paved the way for cutting-edge biomedical research. Its unprecedented success is pushing the frontiers of research, leading numerous research groups and corporations to recognize 3D Slicer as a credible software for designing medical devices. These devices not only have the potential to support routine clinical workflows but may also evolve into marketable products. Although 3D Slicer's development has been largely research-focused, its modular architecture fosters the creation of industrial prototypes.

Systole OS envisions a harmonious integration of 3D Slicer and its associated software, such as the Plus Toolkit, MONAI Label, and others, within a freely accessible, open-source operating system based on GNU/Linux. This aims to facilitate the development and deployment of medical devices.

![](https://projectweek.na-mic.org/PW38_2023_GranCanaria/Projects/SystoleOS/systole.png)

The following are key features we aim to leverage with Systole OS:

1. **State-of-the-Art Software:** Built on the foundation of Gentoo Linux, Systole OS operates on a rolling-release model, ensuring continual, up-to-the-minute updated software.

3. **Easy Installation of Slicer:** With Systole OS, installing Slicer and all its necessary dependencies is as easy as executing a single command (e.g., 'emerge sci-medical/slicer').

4. **Modular Slicer:** The core installation of 3D Slicer will only encompass essential components to run the application, enabling additional modules to be installed separately as needed (e.g., 'emerge slicer-modules/models').

5. **Source-Based Distribution:** Systole OS is derived directly from source code, allowing all packages to be built from source. This gives users the flexibility to make decisions at compile-time, leading to:

    - Improved hardware integration
    - Highly customizable packages (enable/disable certain features)
    - Compatibility with hardware architectures beyond amd64, like ARM and RISC-V.

6. **Extensibility:** Systole OS utilizes the Gentoo overlay system, offering the ability to expand the system with your personal overlay or supersede packages supplied by Systole.

### Objective

1. **Updating Packages:** Ensure the timely update and maintenance of existing packages, targeting specifically the release Slicer-5.3.0.

2. **Integration and Testing Infrastructure:** Develop a robust infrastructure that supports seamless integration and rigorous testing to maintain the highest quality standards.

3. **Generation of Containers and VMs:** Establish a systematic approach for generating containers and Virtual Machines (VMs) that can effectively support both development and testing processes.

### Approach and Plan

1. **Package Assessment:** Review the status of existing packages and identify necessary updates for the release Slicer-5.3.0.

2. **Update Planning:** Develop a plan and timeline for implementing the necessary updates.

3. **Update Implementation:** Carry out the plan to update packages in line with the established timeline.

4. **Kubernetes Infrastructure Setup:** Begin the process of setting up a Kubernetes-based infrastructure to support our integration and testing needs.

5. **Testing Protocol Development:** With the Kubernetes infrastructure ready, establish systematic protocols for integration and testing to ensure high quality standards.

6. **Container and VM Generation:** Implement a systematic approach for creating containers and Virtual Machines (VMs) for development and testing, ensuring this approach is scalable as needed.

### Progress and Next Steps

1. Describe specific steps you **have actually done**.

**Comment by pieper** [comment]
@RafaelPalomar have you looked at conan?  E.g. https://conan.io/center/itk?os=Linux&tab=recipe ?

It could be useful and has the advantage of being cross platform.

**Comment by RafaelPalomar** [comment]
@pieper thanks for letting me know. I need to have a more in-depth look at conan, it's been on my radar for some time now.

**Comment by pieper** [comment]
Makes it sound so easy...

https://chat.openai.com/share/9e596556-c973-4792-9968-745df248cab3
