### ISSUE TITLE
Proposal: Statistical Shape Modeling with Slicer and ShapeWorks

### ISSUE THREAD

**Issue by jessdtate** [NA-MIC/ProjectWeek#827]
### Project Description

Statistical shape modeling (SSM) is fundamental for quantifying and understanding morphological variations correlated with various biological processes, such as morphogenesis, function, adaptation, and disease.  SSM is can be used in impacts a wide spectrum of clinical applications, including pre- and post-operative surgical planning, reconstructive surgery, and design of optimal patient-specific implants and bone surrogates and spacers.   Clinical research entailing large cohorts also benefits from population-level SSM.  

As the need for SSM in clinical applications and large data analysis grows, the need for reliable and easy to use tools becomes more imminent.  While technology and capabilities of SSM have continually expanded, we have focused the development of ShapeWorks on incorporating these latest technologies with UX and UI designed for ease-of-use.  One of the products of this effort is an interface between ShapeWorks and Slicer through Slicer's plugin architecture, expanding the capabilities of both tools.  

We propose a compilation of tutorials of SSM tools to provide an introductory skillset to participants looking to incorporate SSM into their research or to broaden their understanding of the available technologies.  Offering tutorials on the use of ShapeWorks and other Slicer SSM integrations (e.g. SlicerSalt) will empower new SSM users to incorporate these tools into their pipelines and to open more doors of exploration.  Additionally, these tutorials will provide a baseline understanding of the common capabilities of available software to lay a foundation for continued collaboration between SSM researchers including: developing common datatypes and standards, SSM evaluation metrics, and testing pipelines.

**Comment by mauigna06** [comment]
Very interesting :)
For sure I'll check out the SSM tutorials for Slicer when they are ready

**Comment by sjh26** [comment]
@jessdtate 

If you are still intending to do this project, please create a project issue.

**Comment by jessdtate** [comment]
@sjh26  - project issue [created](https://github.com/NA-MIC/ProjectWeek/issues/963)

I initially marked it as a draft, so I'm not sure how to trigger page creation

**Comment by sjh26** [comment]
Closed with #964
