### ISSUE TITLE
Proposal: Multimodal Open source Database for further reasearch analysis

### ISSUE THREAD

**Issue by mariamonzon** [NA-MIC/ProjectWeek#855]
### Project Description

# Project Description

Despite various existing solutions for Medical Database,, including mirroring PACS like XNAT, the storage of medical records. 
However, there exist ( to the best of my limited knowledge) little open sources solutions that can store multimodal data (Electronic Health Records, Medical Imaging data, patient health related data) for clinical research. 
One of the open solutions that I found is to configure a MongoDB database as a backend for ORTHANC PACS Server

## Presenter Location
In-person

## Project Idea

The proposed project aims to create a multimodal medical database with the possibility to export to an structured format ( e.g. the Brain Imaging Data Structure BIDS format), integrating Magnetic Resonance Imaging (MRI) (maybe in DICOM but would support NIFTI conversion), Electronic Health Records (EHR), and sociodemographic data. This database will be designed to assist AI enabled interactive annotation. Additionally the database would include visualizing capabilities (e.g., descriptive statistics).

## Objectives
This project aims to develop an open-source and ideally community-maintained solution for 
- Data Standardization: All collected data will be converted and standarized into research format (e.g.  BIDS format) 
- Having a multimodal research database or integration of medical records with ORTHANC Database. 
- The infrastructure would enable connection to annotation tools such as MONAI Label. 

## Dataset
We can use the MIMIC-IV Dataset with genertaed in this publication:
 https://physionet.org/content/haim-multimodal/1.0.1/

## Disclaimer
I am really new to the community and I would love feedback! I appologize if maybe similar solutions have been explored or there are overlapping projects. 
Thanks for your support

**Comment by sjh26** [comment]
@mariamonzon 

If you are still intending to do this project, please create a project issue.
