### ISSUE TITLE
Surgical planning system for colorectal surgery

### ISSUE THREAD

**Issue by dcaballerojorna** [NA-MIC/ProjectWeek#867]
### Project Description

The objective of this project is to implement the required tools for the development of a surgical planning system for colorectal interventions. These tools are based on CT studies using 3D slicer as a graphical support and python as a programming language.

**Comment by jasanchezmargallo** [comment]
We will provide more details in the coming weeks.
Thank you!

**Comment by jasanchezmargallo** [comment]
The general idea is to implement a semi-automatic method of the colon anatomy using a CT scan under Slicer 3D platform.
This 3D model of the colon will be used for marking interest points such as lesions (polyps and tumors) and resection planes for the subsequent surgical intervention.
Surgeons will have access using Mixed Reality (HoloLens) to the holographic information of both the 3D model of the colon and the interest marks before surgery and at the same OR.
You can see the preliminary results of the semi-automatic method for colon segmentation in the attached video.

 <video
   controls muted
   src="https://github.com/NA-MIC/ProjectWeek/assets/14211856/03a81e35-974e-423b-b530-21f4f0f0f480"
   style="max-height:640px; min-height: 200px">
 </video>

**Comment by RafaelPalomar** [comment]
@dcaballerojorna, this project looks very interesting and can have some synergies with some of the work we have done in previous PW in Slicer-Liver ([https://projectweek.na-mic.org/PW39_2023_Montreal/Projects/SlicerLiver/](https://projectweek.na-mic.org/PW39_2023_Montreal/Projects/SlicerLiver/)).

@jasanchezmargallo, I'm glad to see you in the PW ecosystem :)

**Comment by jasanchezmargallo** [comment]
@RafaelPalomar great to see you! :)
We are new in this arena, but we are sure we can learn a lot and develop fabulous ideas in collaboration.
Looking forward to seeing you next Tuesday :)

**Comment by sjh26** [comment]
closed with #935
