### ISSUE TITLE
Proposal: finalize support for Visible Human DICOM color images in Slicer

### ISSUE THREAD

**Issue by pieper** [NA-MIC/ProjectWeek#875]
### Project Description

3D Slicer reads the VHP pixel data, but the geometry is incorrect. I traced this to the way GDCM treats SC data. Fixes have been proposed but need to be finalized.

[InsightSoftwareConsortium/ITK#4109](https://github.com/InsightSoftwareConsortium/ITK/issues/4109)

[InsightSoftwareConsortium/ITK#4108](https://github.com/InsightSoftwareConsortium/ITK/issues/4108)

[InsightSoftwareConsortium/ITK#4110](https://github.com/InsightSoftwareConsortium/ITK/pull/4110)

@jcfr - can you and I set aside a bit of time to work through this?  @fedorov asked me to try to finish this effort this month.  It shouldn't be much work.

**Comment by fedorov** [comment]
@jcfr will you have time to help with this?

Steve, are you waiting to hear from JC before creating the project page?

It would be nice for IDC to have this issue finally resolved.

**Comment by pieper** [comment]
Yes, I was thinking I would hear from Jc and that would ping me to make a page, but since I can sort this out on my own so if he won't have time maybe this isn't a good project week project after all.  It's just a matter of me allocating the time and energy.

**Comment by sjh26** [comment]
@pieper 

If you are still intending to do this project, please create a project issue.

**Comment by jcfr** [comment]
On a reduced schedule until the end of the week, I am catching up on message et al.

If that still makes sense, happy to spend some time on this.

**Comment by pieper** [comment]
Thanks Jc.  Maybe we can just chat about this when we are together.

**Comment by fedorov** [comment]
Thank you @jcfr - it would be good to resolve this, it's been pending for quite some time, and I am afraid if it is not addressed this PW it is not going to have any attention until the next one.
