### ISSUE TITLE
Proposal: Tutorials on working with DICOM annotations in pathology WSI

### ISSUE THREAD

**Issue by DanielaSchacherer** [NA-MIC/ProjectWeek#876]
### Project Description

This project aims to create tutorials on how to work with DICOM annotations in pathology whole-slide images (WSIs). We will focus on region annotations stored as DICOM Structured Reports for a dataset of Rhabdomyosarcoma, which was recently ingested into the Imaging Data Commons (IDC). 
If time permits we will continue working on nuclei annotations stored as DICOM Microscopy Bulk Simple Annotations. This work was started in the last project week in Montreal, but hindered by technical issues (see [here](https://projectweek.na-mic.org/PW39_2023_Montreal/Projects/TutorialsOnWorkingWithDicomAnnotationsInPathologyWholeSlideImages/)).

**Comment by sjh26** [comment]
closed with #936
