### ISSUE TITLE
Proposal: Current state of DICOMweb for pathology 

### ISSUE THREAD

**Issue by DanielaSchacherer** [NA-MIC/ProjectWeek#877]
### Project Description

This project aims at getting a detailed understanding of the capabilities of available (Python) libraries and tools that implement DICOMweb and how they facilitate working with pathology whole-slide images (WSI) via DICOMweb services. The summarized knowledge should be the basis to decide what further work makes sense (e.g. new library, contributing specific functionality to an existing library etc.).

**Comment by sjh26** [comment]
closed with #937
