### ISSUE TITLE
Proposal: Evaluation of prostate cancer segmentation methods on publicly available data in IDC

### ISSUE THREAD

**Issue by deepakri201** [NA-MIC/ProjectWeek#889]
### Project Description

When it comes to evaluating AI methods, it's important to have reproducible code and methods. 

We are interested in evaluating state-of-the-art methods for prostate cancer segmentation on data in Imaging Data Commons. We've identified a set of publicly available methods from PICAI, and MONAI (bundle and deploy app) for segmentation, and have started evaluating these on data in IDC. 

We'd like to do a more comprehensive evaluation and demonstrate our workflow.

**Comment by fedorov** [comment]
In addition to IDC, we have an internal non-public BWH dataset that we plan to use as well!

@JoostJM didn't you say you are working on prostate cancer application these days, or did I confuse you with someone else?

@nolden any interest or pointers from DKFZ, including what tools we should consider, given your track record in this area?
