### ISSUE TITLE
Proposal: Investigating the role of public imaging data in research

### ISSUE THREAD

**Issue by fedorov** [NA-MIC/ProjectWeek#891]
### Project Description

I had the idea to use PW as a venue to collect information about the role of public image data in the PW community:
* how public is used data is used
* what are the sources of public data that are utilized
* what are the expectations from the public data repositories
* what are the limitations that limit utility of the existing public datasets and existing repositories of such datasets

I was thinking to first discuss with anyone interest to come up with a form to collect this information, solicit responses from the attendees and report on the responses at the end of the week. Depending how this goes, we can expand this survey beyond the project week audience, and even write a preprint/paper about this.

The results of this study may help influence development of repositories and future data collection efforts.

I discussed this idea with @pieper, and he is supportive!

**Comment by fedorov** [comment]
Note to myself - add @ulrikew to the project!

**Comment by pieper** [comment]
Shall we start a google form or google doc as a place to collect ideas for what information we want to collect?

One topic I'd like to learn more about is what researchers think of the role of public image repositories in demonstrating best practices in terms of data organization and standards.

**Comment by tkapur** [comment]
Yes. I also wonder if a miccai workshop may be useful on the topic.

**Comment by fedorov** [comment]
Thanks for all the feedback and interest! I will set up a doc and link from the project page that I need to set up.

**Comment by fedorov** [comment]
This looks relevant - need to read: Woznicki, P., Laqua, F. C., Al-Haj, A., Bley, T. & Baeßler, B. Addressing challenges in radiomics research: systematic review and repository of open-access cancer imaging datasets. Insights Imaging 14, 1–13 (2023).

**Comment by ulrikew** [comment]
> This looks relevant - need to read: Woznicki, P., Laqua, F. C., Al-Haj, A., Bley, T. & Baeßler, B. Addressing challenges in radiomics research: systematic review and repository of open-access cancer imaging datasets. Insights Imaging 14, 1–13 (2023).

They built their own database: https://radiomics.uk/ with the extracted datasets

**Comment by fedorov** [comment]
Superseded by #943
