### ISSUE TITLE
Add a MONAI Auto3DSeg inference extension to 3DSlicer 

### ISSUE THREAD

**Issue by rbumm** [NA-MIC/ProjectWeek#914]
### Draft Status

Ready - team will start page creating immediately

### Category

Segmentation / Classification / Landmarking

### Presenter Location

In-person

### Key Investigators

- Rudolf Bumm (Cantonal Hospital of Graubünden, Switzerland)
- Andras Lasso (Queens University, USA)
- Andres Diaz-Pinto (Senior Deep Learning Engineer at NVIDIA, UK)   

### Project Description

This project aims to implement MONAI Auto3DSeg in a 3DSlicer extension. This will enable fast inference with NVIDIA GPUs and CUDA and slower inference with CPU only. 
Auto3DSeg is a relatively new technique in the MONAI project and our first experiments have been successful inference is not as complicated as using the MONAOLabel inference function.  
A future aim is to integrate Auto3DSeg training into the MONAILabel extension. 

### Objective

1. Objective A. Implement Auto3DSeg into a new 3D Slicer extension. 

### Approach and Plan

We have great starting code as well as 2 ready-to-use models from Andres Diaz-Pinto. We will build on that. 
In addition, we will train a lung lobe and airway model which should be available at the PW. 

### Progress and Next Steps

1. Creating 2 Auto3DSeg models ready to use. 

### Illustrations

Algorithm Generation: 
![image](https://github.com/NA-MIC/ProjectWeek/assets/18140094/286ae610-4ab7-4352-ac80-ab4d2c4773c1)

Simulate a dataset and Auto3D datalist using MONAI functions: 
![image](https://github.com/NA-MIC/ProjectWeek/assets/18140094/6208629d-5a2f-4c39-a98a-0b0a98367546)

### Background and References

https://github.com/Project-MONAI/tutorials/tree/main/auto3dseg#performance-benchmarking

**Comment by rbumm** [comment]
Closing.

**Comment by sjh26** [comment]
It looks like you closed this by accident, will re-open and start the page generation

**Comment by rbumm** [comment]
Thank you, Sam !

Am Di., 16. Jan. 2024 um 20:39 Uhr schrieb Sam Horvath <
***@***.***>:

**Comment by rbumm** [comment]
Of course not!
Feel yourself invited.
Best
Rudolf

Am Di., 16. Jan. 2024 um 21:50 Uhr schrieb Steve Pieper <
***@***.***>:
