### ISSUE TITLE
Proposal: Long-COVID and the Brain White Matter 

### ISSUE THREAD

**Issue by zora2** [NA-MIC/ProjectWeek#923]
### Project Description

About 10% of COVID-19 survivors experience long-lasting symptoms known as long-COVID. The debilitating symptoms of PASC impact patient’s health-related quality of life, earnings, caretaking activities for loved ones, and healthcare costs. There is no proven cure for PASC. Amongst the variable sequelae of long-COVID, the neuropsychiatric subtype of long-COVID (neuro-long-COVID) is characterized by fatigue, cognitive impairments, and pro-inflammatory cytokines. Our research project aims to understand how changes in the brain, specifically the white matter, contribute to the symptoms of the neuropsychiatric subtype of long-COVID.

We are particularly interested in the brain white matter fiber system that we term the dorsal vagal complex-corticolimbic fiber system (DVC-CLFS; Kikinis et al., in press). This fiber system interconnects cortical, paralimbic, limbic, and autonomic brain regions. It integrates them with bodily organs via the brainstem and the vagal nerve (Kikinis et al., in press). The DVC-CLFS underlies brain-immune interactions and involves several centers in the brainstem. The principal fiber tract in the DVC-CFLS is the medial forebrain bundle (MFB).

While we have previously reconstructed the MFB, our new approach allows us to rebuild the streamlines reaching the brainstem. Using the Harvard Oxford Atlas (HOA), we will use whole brain tractography from 10 patients with long-COVID to select the Medial Forebrain Bundle (MFB) at its entire extension.

As part of the project, we will demonstrate the method to reconstruct the MFB. We will offer tutorial of 3DSlicer of segmentation, reconstruction of brain white matter streamlines from whole brain tractography and a video demonstration of the application of the Harvard Oxford Atlas.

**Comment by sjh26** [comment]
Closed with #925
