### ISSUE TITLE
Project: NVIDIA Holoscan and 3D Slicer

### ISSUE THREAD

**Issue by brudfors** [NA-MIC/ProjectWeek#938]
### Draft Status

Ready - team will start page creating immediately

### Category

Infrastructure

### Presenter Location

In-person

### Key Investigators

- Mikael Brudfors (NVIDIA, UK)

### Project Description

This project aims at integrating [NVIDIA Holoscan](https://developer.nvidia.com/holoscan-sdk) into 3D Slicer. Holoscan is a hybrid computing platform for medical devices that combines hardware systems for low-latency sensor and network connectivity, optimized libraries for data processing and AI, and core microservices to run surgical video, ultrasound, medical imaging, and other applications anywhere, from embedded to edge to cloud. 

### Objective

Integrate Holoscan with 3D Slicer. As Holoscan is both a hardware platform ([NVIDIA IGX Orin](https://www.nvidia.com/en-gb/edge-computing/products/igx/)) and an SDK ([Holoscan SDK](https://github.com/nvidia-holoscan/holoscan-sdk)) the integration could be of either of these components, or both.

### Approach and Plan

There are various options, not yet sure which one is the best (or if there are ones I have not considered):
1. Use OpenIGTLink to stream data from a Holoscan developer kit to 3D Slicer, over network. This would bypass the fact that 3D Slicer does not easily build on ARM (which is the arch of the IGX Orin).
2. Create operators in 3D Slicer that can pass data to and from Holoscan SDK. This would give a 3D Slicer user access to the API of Holoscan SDK for efficient AI inference, etc.
3. Connect an IGX Orin running Holoscan SDK to the [Plus toolkit](https://plustoolkit.github.io/).

**Comment by pieper** [comment]
This looks great @brudfors - look forward to chatting about the options.  Add me to the project if you want.

**Comment by RafaelPalomar** [comment]
@brudfors, I'd be happy to join too. I'm glad you will join PW in person.

**Comment by brudfors** [comment]
Thanks @pieper and @RafaelPalomar! I will add you to the project then, looking forward to getting some of your input!
